# file: dotfiles.yml
- name: Set up local workstation
  hosts: local
  roles:
    - role: configs
    - role: packages
    - role: zsh
  vars:
    HOME: "{{ lookup('env', 'HOME') }}"
    ROOTDIR: "{{ lookup('env', 'ROOTDIR') }}"