---
# file: roles/packages/tasks/main.yml

# This is meant to run on Manjaro Openbox https://manjaro-community.osdn.io/openbox/

- name: Installs packages | pacman
  become: yes
  become_user: root
  become_method: sudo
  pacman:
    name:
      - chromium
      - code
      - gitahead
      - yarn
    state: present
    update_cache: yes