---
# file: roles/zsh/tasks/main.yml

# This is meant to run on Manjaro Openbox https://manjaro-community.osdn.io/openbox/

- name: Create directories if they don't exist
  become: yes
  become_user: davideu
  become_method: sudo
  file:
    path: "{{ item }}"
    state: directory
    owner: davideu
    group: davideu
    mode: 0775
  with_items:
  - "{{ HOME }}/.local/bin/"

- name: Checks for zimfw installation | stat
  become: yes
  become_user: davideu
  become_method: sudo
  stat:
    path: "{{ HOME }}/.zim"
  register: zimfw

- name: Installs zimfw | raw
  become: yes
  become_user: davideu
  become_method: sudo
  raw: 'curl -fsSL https://raw.githubusercontent.com/zimfw/install/master/install.zsh | zsh'
  when: not zimfw.stat.exists

- name: Links .zshrc file | file
  become: yes
  become_user: davideu
  become_method: sudo
  file:
    src: "{{ ROOTDIR }}/roles/zsh/files/zshrc.link"
    dest: "{{ HOME }}/.zshrc"
    state: link
    force: yes

- name: Checks for pyenv installation | stat
  become: yes
  become_user: davideu
  become_method: sudo
  stat:
    path: "{{ HOME }}/.pyenv"
  register: pyenv

- name: Installs pyenv | raw
  become: yes
  become_user: davideu
  become_method: sudo
  raw: 'url https://pyenv.run | bash'
  when: not pyenv.stat.exists

- name: Display paths of all .link files in dir bin
  debug: msg={{ lookup('fileglob', '{{ ROOTDIR }}/roles/zsh/files/bin/*.link') }}

- name: Links bin files | file
  become: yes
  become_user: davideu
  become_method: sudo
  file:
    src: "{{ item }}"
    dest: "{{ HOME }}/.local/bin/{{ item | basename | regex_replace('^([^\\.]*).*', '\\1') }}"
    state: link
    force: yes
  with_fileglob: "{{ ROOTDIR }}/roles/zsh/files/bin/*.link"
