---
# file: roles/configs/tasks/main.yml

# This is meant to run on Manjaro Openbox https://manjaro-community.osdn.io/openbox/

- name: Git user.name configuration | git_config
  become: yes
  become_user: davideu
  become_method: sudo
  git_config:
    name: user.name
    scope: global
    value: Davide Ungari

- name: Git user.email configuration | git_config
  become: yes
  become_user: davideu
  become_method: sudo 
  git_config:
    name: user.email
    scope: global
    value: ungarida@gmail.com

- name: Move lxdm theme | copy
  become: yes
  become_user: root
  become_method: sudo
  copy:
    src: "{{ lookup('env', 'ROOTDIR') }}/roles/configs/files/lxdm-theme-dark"
    dest: "/usr/share/lxdm/themes/"
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Move lxdm.conf | copy
  become: yes
  become_user: root
  become_method: sudo
  copy:
    src: "{{ lookup('env', 'ROOTDIR') }}/roles/configs/files/lxdm.lxdm.conf.link"
    dest: "/etc/lxdm/lxdm.conf"
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Links Openbox files | file
  become: yes
  become_user: davideu
  become_method: sudo
  file:
    src: "{{item}}"
    dest: "{{ lookup('env', 'HOME') }}/.config/openbox/{{ item | basename | regex_replace('^(.*)\\.link$', '\\1') }}"
    state: link
    force: yes
  with_fileglob: "{{ lookup('env', 'ROOTDIR') }}/roles/configs/files/openbox/*.link"

- name: Links wallpaper | file
  become: yes
  become_user: davideu
  become_method: sudo
  file:
    src: "{{ lookup('env', 'ROOTDIR') }}/roles/configs/files/daft_punk.wallpaper.2932x2932.jpg"
    dest: "{{ lookup('env', 'HOME') }}/Pictures/wallpaper"
    state: link
    force: yes

- name: Set nitrogen wallpaper | shell
  become: yes
  become_user: davideu
  become_method: sudo
  shell:
    cmd: nitrogen --set-color="#050424" --set-zoom ~/Pictures/wallpaper --save

- name: Links Rofi config.rasi | file
  become: yes
  become_user: davideu
  become_method: sudo
  file:
    src: "{{ lookup('env', 'ROOTDIR') }}/roles/configs/files/rofi.config.rasi.link"
    dest: "{{ lookup('env', 'HOME') }}/.config/rofi/config.rasi"
    state: link
    force: yes

- name: Links Termite config | file
  become: yes
  become_user: davideu
  become_method: sudo
  file:
    src: "{{ lookup('env', 'ROOTDIR') }}/roles/configs/files/termite.config.link"
    dest: "{{ lookup('env', 'HOME') }}/.config/termite/config"
    state: link
    force: yes

- name: Links .xmodmap file | file
  become: yes
  become_user: davideu
  become_method: sudo
  file:
    src: "{{ lookup('env', 'ROOTDIR') }}/roles/configs/files/xmodmap.link"
    dest: "{{ lookup('env', 'HOME') }}/.xmodmap"
    state: link
    force: yes

- name: Loads .xmodmap file | shell
  become: yes
  become_user: davideu
  become_method: sudo
  shell:
    cmd: xmodmap {{ lookup('env', 'HOME') }}/.xmodmap