---
# file: roles/configs/tasks/main.yml

# This is meant to run on Manjaro Openbox https://manjaro-community.osdn.io/openbox/

- name: Git user.name configuration | git_config
  become: yes
  become_user: davideu
  become_method: sudo
  git_config:
    name: user.name
    scope: global
    value: Davide Ungari

- name: Git user.email configuration | git_config
  become: yes
  become_user: davideu
  become_method: sudo 
  git_config:
    name: user.email
    scope: global
    value: ungarida@gmail.com

- name: Links autostart file | file
  become: yes
  become_user: davideu
  become_method: sudo
  file:
    src: "{{ lookup('env', 'ROOTDIR') }}/roles/configs/files/openbox.autostart.link"
    dest: "{{ lookup('env', 'HOME') }}/.config/openbox/autostart"
    state: link
    force: yes

- name: Links lxdm.conf | file
  become: yes
  become_user: root
  become_method: sudo
  file:
    src: "{{ lookup('env', 'ROOTDIR') }}/roles/configs/files/lxdm.conf.link"
    dest: "/etc/lxdm/lxdm.conf"
    state: link
    force: yes

- name: Links nitrogen.cfg | file
  become: yes
  become_user: davideu
  become_method: sudo
  file:
    src: "{{ lookup('env', 'ROOTDIR') }}/roles/configs/files/nitrogen.cfg.link"
    dest: "{{ lookup('env', 'HOME') }}/.config/nitrogen/nitrogen.cfg"
    state: link
    force: yes

- name: Links wallpaper | file
  become: yes
  become_user: davideu
  become_method: sudo
  file:
    src: "{{ lookup('env', 'ROOTDIR') }}/roles/configs/files/daft_punk.wallpaper.2932x2932.jpg"
    dest: "{{ lookup('env', 'HOME') }}/Pictures/wallpaper"
    state: link
    force: yes

- name: Links nitrogen bg-saved.cfg | file
  become: yes
  become_user: davideu
  become_method: sudo
  file:
    src: "{{ lookup('env', 'ROOTDIR') }}/roles/configs/files/nitrogen.bg-saved.cfg.link"
    dest: "{{ lookup('env', 'HOME') }}/.config/nitrogen/bg-saved.cfg"
    state: link
    force: yes

- name: Set nitrogen wallpaper | shell
  become: yes
  become_user: davideu
  become_method: sudo
  shell:
    cmd: nitrogen --set-color="#050424" --set-zoom ~/Pictures/wallpaper --save

- name: Links .xmodmap file | file
  become: yes
  become_user: davideu
  become_method: sudo
  file:
    src: "{{ lookup('env', 'ROOTDIR') }}/roles/configs/files/xmodmap.link"
    dest: "{{ lookup('env', 'HOME') }}/.xmodmap"
    state: link
    force: yes

- name: Loads .xmodmap file | shell
  become: yes
  become_user: davideu
  become_method: sudo
  shell:
    cmd: xmodmap {{ lookup('env', 'HOME') }}/.xmodmap