---
# file: roles/openbox/tasks/main.yml

# This is meant to run on Manjaro Openbox https://manjaro-community.osdn.io/openbox/

- name: Links .xmodmap file | file
  become: yes
  become_user: davide
  become_method: sudo
  file:
    src: "{{ lookup('env', 'ROOTDIR') }}/roles/openbox/files/xmodmap.link"
    dest: "{{ lookup('env', 'HOME') }}/.xmodmap"
    state: link
    force: yes